# Generated by Django 6.0.5 on 2026-05-29 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_historialprecio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['marca', 'modelo', 'anio'],
                'unique_together': {('marca', 'modelo', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='Compatibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, help_text='Ej: "sirve adaptando soporte"', max_length=300)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades', to='catalogo.producto')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades', to='compatibilidades.vehiculo')),
            ],
            options={
                'verbose_name_plural': 'Compatibilidades',
                'unique_together': {('vehiculo', 'producto')},
            },
        ),
    ]
