# Generated by Django 6.0.5 on 2026-05-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TallerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Taller', max_length=200)),
                ('domicilio', models.CharField(blank=True, max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Configuración del taller',
                'verbose_name_plural': 'Configuración del taller',
            },
        ),
    ]
